# Commands go through bash
shell = "bash -c '{}'"

# Sway supports the default '#' comments, so it can be ommited
# 'rewrite' is also ommited, as it defaults to false
[[item]]
file = "~/.config/sway/config.d/00-colors.conf"
rewrite = true
template = "sway"
subtemplate = "colors"
hook = "~/.dotfiles/scripts/reload-sway-colors.sh"

# This one uses waybar 'default' subtemplate, so it can be ommited
[[item]]
file = "~/.config/waybar/colors.css"
template = "waybar"
# Waybar uses a separate color file, so we can safely rewrite the whole file
rewrite = true
hook = "pkill waybar; waybar & disown"

[[item]]
file = "~/.config/kitty/base16.conf"
template = "kitty"
rewrite = true
hook = "kitty @ set-colors -a '~/.config/kitty/base16.conf'"

[[item]]
file = "~/.config/dunst/dunstrc"
template = "dunst"
hook = "killall dunst"

[[item]]
file = "~/.config/lvim/config.lua"
template = "lua"
start = "-- Start flavours"
end = "-- End flavours"

[[item]]
file = "~/.config/rofi/launchers/colorful/style_2.rasi"
template = "rofi"
subtemplate = "colors"
start = "/* Start flavours */"
end = "/* End flavours */"

[[item]]
file = "~/.config/zathura/zathurarc"
template = "zathura"
start = "# Start flavours"
end = "# End flavours"

[[item]]
file = "~/.local/share/flavours/materia-theme/gtk-colors"
template = "materiatheme"
rewrite = true
hook = "~/.local/share/flavours/materia-theme/change_color.sh -o Materia ~/.local/share/flavours/materia-theme/gtk-colors -i False -t ~/.themes/; gsettings set org.gnome.desktop.interface gtk-theme dummy && gsettings set org.gnome.desktop.interface gtk-theme Materia"

