theme = "dracula"
client_id_command = { command = "printenv", args = [
  "SPOTIFY_PLAYER_APP_CLIENT_ID",
] }
client_port = 8080
login_redirect_uri = "http://127.0.0.1:8989/login"
playback_format = """
{status} {track} • {artists}
{album}
{metadata}"""
notify_timeout_in_secs = 0
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
page_size_in_rows = 20
border_type = "Plain"
progress_bar_type = "Rectangle"
cover_img_length = 9
cover_img_width = 5
cover_img_scale = 1.0
enable_media_control = true
enable_streaming = "Always"
enable_notify = false
enable_cover_image_cache = true
default_device = "spotify-player"
notify_streaming_only = false
seek_duration_secs = 5
sort_artist_albums_by_type = false
play_icon = "󰐊"
pause_icon = "󰏤"
liked_icon = ""

[notify_format]
summary = "{track} • {artists}"
body = "{album}"

[layout]
library = { playlist_percent = 40, album_percent = 40 }
playback_window_position = "Bottom"
playback_window_height = 5


[device]
name = "spotify-player"
device_type = "speaker"
volume = 100
bitrate = 320
audio_cache = false
normalization = false
autoplay = false
