[[manager.prepend_keymap]]
on = ["T"]
run = "plugin max-preview"
desc = "Maximize or restore preview"
[[manager.prepend_keymap]]
on = ["<C-n>"]
run = '''
  shell 'ripdrag "$@" -x 2>/dev/null &' --confirm
'''
[[manager.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "Chmod on selected files"
[[manager.prepend_keymap]]
on = ["g", "w"]
desc = "Set as wallpaper"
run = '''
  shell 'wall.sh "$@" 2>/dev/null &'
'''
