"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[flavor]
dark = "catppuccin-mocha"
light = "catppuccin-latte"

[[icon.prepend_dirs]]
text = ""
name = "Development"

[[icon.prepend_dirs]]
text = ""
name = "Projects"

[[icon.prepend_dirs]]
text = "󱉽"
name = "Obsidian"

[[icon.prepend_dirs]]
text = "󰉎"
name = "Insync"
