#!/bin/bash

xwinwrap -ov -g 3840x2160+0+0 -- mpv -wid WID "$1" --no-osc --no-osd-bar --loop-file --player-operation-mode=cplayer --no-audio --panscan=1.0 --no-keepaspect --no-input-default-bindings --hwdec > /dev/null 2>&1 &

