#!/usr/bin/env bash
# current_java=$(asdf current java | awk '{ print $2; }')

. "$ASDF_DIR"/asdf.sh

asdf shell java liberica-8u302+8
"$ANDROID_HOME"/tools/bin/avdmanager "$@"
ec=$?
asdf shell java --unset
exit $ec
