#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config window_placement second_child
yabai -m config window_opacity on
yabai -m config window_opacity_duration 0.0
yabai -m config window_shadow off
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 1.0
yabai -m config split_ratio 0.66
yabai -m config auto_balance off
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
# yabai -m config window_animation_duration 0.05
# yabai -m config window_animation_easing ease_out_quint

# general space settings
yabai -m config layout bsp
GAP_SIZE=30
yabai -m config top_padding $GAP_SIZE
yabai -m config bottom_padding $GAP_SIZE
yabai -m config left_padding $GAP_SIZE
yabai -m config right_padding $GAP_SIZE
yabai -m config window_gap $GAP_SIZE
yabai -m config external_bar all:42:0
# yabai -m config external_bar                 all:0:0

NOTCH_UUID="37D8832A-2D66-02CA-B9F7-8F30A301B230"
NORMAL_BAR=25
NOTCH_BAR=42

yabai -m signal --add event=display_added action="if [[ \"\$(yabai -m query --displays | jq \".[\$YABAI_DISPLAY_ID].uuid\")\" =~ \"$NOTCH_UUID\" ]]; then yabai -m config external_bar main:$NORMAL_BAR:0; elif [[ \"\$(yabai -m query --displays | jq '.[].uuid')\" =~ \"$NOTCH_UUID\" ]]; then yabai -m config external_bar main:$NORMAL_BAR:0; else yabai -m config external_bar all:$NORMAL_BAR:0; fi"
yabai -m signal --add event=display_removed action="if [[ \"\$(yabai -m query --displays | jq \".[\$YABAI_DISPLAY_ID].uuid\")\" =~ \"$NOTCH_UUID\" ]]; then yabai -m config external_bar all:$NORMAL_BAR:0; elif [[ \"\$(yabai -m query --displays | jq '.[].uuid')\" =~ \"$NOTCH_UUID\" ]]; then yabai -m config external_bar all:$NOTCH_BAR:0; fi"

# global settings
if [[ "$(yabai -m query --displays | jq '.[].uuid')" =~ "$NOTCH_UUID" ]]; then
	if [ "$(yabai -m query --displays | jq length)" -gt "1" ]; then
		yabai -m config external_bar main:$NORMAL_BAR:0
	else
		yabai -m config external_bar all:$NOTCH_BAR:0
	fi
else
	yabai -m config external_bar all:$NORMAL_BAR:0
fi

# per app settings

yabai -m rule --add app=".*" layer=below

yabai -m rule --add app="Home Assistant" manage=off
yabai -m rule --add app="Android Studio" title="Settings" manage=off
yabai -m rule --add app="System Preferences" manage=off layer=above
yabai -m rule --add app="floatterm" manage=off

# fix having no focus when the last of a window of an app in a space is closed
yabai -m signal --add event=window_destroyed action= ~/.dotfiles/scripts/yabai-on-window_destroyed.sh
# fix wezterm not getting focus properly
yabai -m window --focus "$(yabai -m query --windows | jq 'map(select(.app=="WezTerm")) | sort_by(.id) | last.id')"

echo "yabai configuration loaded.."
