#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# bar settings
yabai -m config status_bar                   off
yabai -m config status_bar_text_font         "Helvetica Neue:Regular:16.0"
yabai -m config status_bar_icon_font         "Iosevka Nerd Font:Regular:16.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config window_border                off
yabai -m config window_border_width          10
yabai -m config active_window_border_color   0xff8be9fd
yabai -m config normal_window_border_color   0xff6272a4
yabai -m config insert_window_border_color   0xfff1fa8c
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config split_ratio                  0.66
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  60
yabai -m config bottom_padding               60
yabai -m config left_padding                 60
yabai -m config right_padding                60
yabai -m config window_gap                   60

# per app settings

yabai -m rule --add title="Microsoft Teams Notification" window_border=off
yabai -m rule --add title="Microsoft Teams Notification" manage=off
yabai -m rule --add app="Cardhop" manage=off
yabai -m rule --add app="Home Assistant" manage=off
yabai -m rule --add app="Android Studio" manage=off
yabai -m rule --add app="Android Studio" title="~/" manage=on
yabai -m rule --add app="Android Studio" title="..." manage=on
yabai -m rule --add app="System Preferences" manage=off
yabai -m rule --add app="System Preferences" window_border=off

echo "yabai configuration loaded.."
